from __future__ import annotations

import logging
import shutil
from pathlib import Path

from vivado_mcp.config import (
    find_vivado,
    generate_auth_token,
    installed_server_script,
    load_auth_token,
    save_auth_token,
)
from vivado_mcp.vivado.gui_session import _locate_server_script

logger = logging.getLogger(__name__)

_BEGIN_MARK = "## ===== vivado-mcp injection begin ====="
_END_MARK = "## ===== vivado-mcp injection end ====="
_BACKUP_SUFFIX = ".vmcp_backup"


def _resolve_init_tcl(vivado_path: str | None) -> Path:
    exe = Path(find_vivado(vivado_path)).resolve()
    vivado_root = exe.parent.parent
    return vivado_root / "scripts" / "Vivado_init.tcl"


def _remove_injection(content: str) -> str:
    lines = content.splitlines(keepends=True)
    result: list[str] = []
    in_block = False
    for line in lines:
        if _BEGIN_MARK in line:
            in_block = True
            continue
        if _END_MARK in line:
            in_block = False
            continue
        if not in_block:
            result.append(line)
    return "".join(result)


def _prepare_server_script(dev_mode: bool) -> tuple[Path, str]:
    source_script = _locate_server_script()
    if dev_mode:
        return source_script, "dev"

    target_script = installed_server_script()
    target_script.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_script, target_script)
    return target_script, "stable"


def _build_injection_block(server_script: Path, port: int, auth_token: str, mode_label: str) -> str:
    script_posix = server_script.as_posix()
    return (
        f"{_BEGIN_MARK}\n"
        "## Generated by `vivado-mcp install`.\n"
        f"## Install mode: {mode_label}.\n"
        "## The server binds to 127.0.0.1 only and requires VMCP_AUTH_TOKEN.\n"
        f"set ::VMCP_PORT_PREF {port}\n"
        f"set ::VMCP_AUTH_TOKEN {{{auth_token}}}\n"
        f'if {{[catch {{source "{script_posix}"}} __vmcp_err]}} {{\n'
        '    puts "vivado-mcp: init server load failed: $__vmcp_err"\n'
        "}\n"
        f"{_END_MARK}\n"
    )


def install(
    vivado_path: str | None = None,
    port: int = 9999,
    auth_token: str | None = None,
    dev_mode: bool = False,
) -> None:
    init_tcl = _resolve_init_tcl(vivado_path)
    server_script, mode_label = _prepare_server_script(dev_mode)

    content = ""
    if init_tcl.is_file():
        content = init_tcl.read_text(encoding="utf-8", errors="replace")

    if _BEGIN_MARK in content:
        content = _remove_injection(content)

    token = (auth_token or load_auth_token() or generate_auth_token()).strip()
    token_path = save_auth_token(token)

    backup_path = init_tcl.with_suffix(init_tcl.suffix + _BACKUP_SUFFIX)
    if init_tcl.is_file() and not backup_path.is_file():
        shutil.copy2(init_tcl, backup_path)

    injection = _build_injection_block(server_script, port, token, mode_label)
    new_content = content.rstrip() + "\n\n" + injection
    init_tcl.write_text(new_content, encoding="utf-8")

    print(f"Vivado init.tcl: {init_tcl}")
    print(f"Server script:    {server_script}")
    print(f"Install mode:     {mode_label}")
    print(f"Port preference:  {port}")
    print(f"Auth token file:  {token_path}")
    if dev_mode:
        print("Dev mode tracks the current working tree. Restart Vivado after code changes.")
    else:
        print("Stable mode uses a copied script. Re-run `vivado-mcp install` after updating features.")
    print("vivado-mcp injection installed successfully.")


def uninstall(vivado_path: str | None = None) -> None:
    try:
        init_tcl = _resolve_init_tcl(vivado_path)
    except FileNotFoundError as exc:
        print(f"Vivado not found: {exc}")
        return

    if not init_tcl.is_file():
        print(f"{init_tcl} does not exist, nothing to do.")
        return

    content = init_tcl.read_text(encoding="utf-8", errors="replace")
    if _BEGIN_MARK not in content:
        print(f"{init_tcl} has no vivado-mcp injection, nothing to do.")
        return

    cleaned = _remove_injection(content).rstrip() + "\n"
    init_tcl.write_text(cleaned, encoding="utf-8")
    print(f"Removed vivado-mcp injection from {init_tcl}.")

    backup_path = init_tcl.with_suffix(init_tcl.suffix + _BACKUP_SUFFIX)
    if backup_path.is_file():
        print(f"Original backup remains at {backup_path}")
